// <auto-generated />
using System;
using Infrastucture;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(CaminhaoContext))]
    [Migration("20210331085558_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Caminhao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("anoFabricacao")
                        .HasColumnName("AnoFabricacao");

                    b.Property<int>("anoModelo")
                        .HasColumnName("AnoModelo");

                    b.Property<int?>("caminhaoModeloid");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(256)");

                    b.HasKey("id");

                    b.HasIndex("caminhaoModeloid");

                    b.ToTable("Caminhao");
                });

            modelBuilder.Entity("Domain.CaminhaoModelo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ativo");

                    b.Property<string>("sigla")
                        .IsRequired()
                        .HasColumnName("Sigla")
                        .HasColumnType("varchar(2)");

                    b.HasKey("id");

                    b.ToTable("CaminhaoModelo");
                });

            modelBuilder.Entity("Domain.Caminhao", b =>
                {
                    b.HasOne("Domain.CaminhaoModelo", "caminhaoModelo")
                        .WithMany()
                        .HasForeignKey("caminhaoModeloid");
                });
#pragma warning restore 612, 618
        }
    }
}
